### ISSUE TITLE
Standardize line ending behavior

### ISSUE THREAD

**Issue by ashander** [ropensci/opendata#97]
As illustrated in #96 an otherwise helpful pull request can be jammed up by line endings. We can fix this for the repository in general as outlined here https://help.github.com/articles/dealing-with-line-endings/
but I'm not sure what's best practice. @leeper or @sckott have you dealt with this issue in other ropensci repos?

**Comment by sckott** [comment]
hmm, haven't had any repos with lots of PRs, don't know good soln

**Comment by leeper** [comment]
Adding a .gitattributes file sounds like a good idea, since this has become a consistent problem.

**Comment by jennybc** [comment]
Which sorts of line endings are the problem? Windows (`\r\n`) or classic Mac (`\r`)? Git has nice options to finesse the former but the latter ... not so much. That said, I only battle against `\r` with spreadsheet exports, so maybe you don't suffer from that.

**Comment by ashander** [comment]
Thanks for the endorsement all. I'll do it.

Re @jennybc any differences across OS can cause issues, but are I guess classic macs relatively rare. There are, apparently, three types of endings: `CR` (classic mac), `CRLF` (win), and `LF` (unix, modern mac). [This blog post from Tim Clem](http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/) has way more info than anyone needs on git and line-endings.

I'm hoping adding an appropriate .gitattributes will resolve this either way. That is, even if someone on a classic mac submits a PR.

**Comment by ashander** [comment]
Think a simple gitattributes fixed this, which I did in 6605d07

I tried to test this in #111, but I realize as I typed this comment that the machine I 'tested' it on had global line endings properly configured (as specified in https://help.github.com/articles/dealing-with-line-endings/#platform-linux). So I'm not really sure it's fixed ...

**Comment by leeper** [comment]
So, I think this is fixed, except that I just noticed when testing that the `sed` calls appear to change the line endings in README from `\r\n` (generated using Gnu sed on windows) to just `\n` and I can't figure out how to fix that.

**Comment by ashander** [comment]
I think the sed thing isn't an issue. Looking through, the only consistently mixed line endings file was opendata.md. With the .gitmodules introduced in 6605d07 we maintain this. All other files have had unix `\n` endings for a while. I explored this a bit in branch `fix/line-end`. 

For now, closing and we'll keep mixed line endings only in opendata.md

**Comment by ashander** [comment]
Seems this isn't actually fixed (based on huge diffs in opendata.md in PRs #126 and #124)

**Comment by ashander** [comment]
I think the new .gitattributes will work https://github.com/git/git/blob/master/Documentation/RelNotes/2.10.0.txt#L248-L254

**Comment by ashander** [comment]
Ugh. I was wrong. I'd set it up incorrectly and the attribute in 0a96f71 
 `opendata.md eol=crlf` doesn't have any effect.

 `opendata.md text eol=crlf` (per https://help.github.com/articles/dealing-with-line-endings/) would make `opendata.md` always have `crlf` endings on checkout. but that doesn't seem to be what we really want, and on my machine results in git wanting to check in a change for every line. exactly what we don't want! grr. 

so now we're back to the simple .gitattributes from before, but from #209 it's clear this won't always enforce the correct behavior
